name: tfg_ivandelllanoblanco
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  url_launcher: ^6.3.1
  syncfusion_flutter_charts: ^28.2.12
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  fl_chart: ^0.71.0
  flutter_spinkit: ^5.2.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/oso.riv
    - assets/imagendefecto.png
    - assets/microsoftLogo.png
    - assets/logoGoogle.png
